// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxpIYkXX7MCa435ALte1wpK-ykpQx_MA4',
    appId: '1:209697579098:web:135804f450c85b6b3a7863',
    messagingSenderId: '209697579098',
    projectId: 'homelog-95dca',
    authDomain: 'homelog-95dca.firebaseapp.com',
    storageBucket: 'homelog-95dca.appspot.com',
    measurementId: 'G-XDRWQ018DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9v2tr1DfrSHEvf66CLi2NNrGQzugfJRQ',
    appId: '1:209697579098:android:23916412abb86e293a7863',
    messagingSenderId: '209697579098',
    projectId: 'homelog-95dca',
    storageBucket: 'homelog-95dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlgstTJBd0-hTlW-lCm9Gm5FYiCHfZs-k',
    appId: '1:209697579098:ios:881033e94d04ea8b3a7863',
    messagingSenderId: '209697579098',
    projectId: 'homelog-95dca',
    storageBucket: 'homelog-95dca.appspot.com',
    iosClientId: '209697579098-l0pdhig055o98fng16vggfo0lslhkpve.apps.googleusercontent.com',
    iosBundleId: 'com.example.p',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlgstTJBd0-hTlW-lCm9Gm5FYiCHfZs-k',
    appId: '1:209697579098:ios:57426947396b6fc13a7863',
    messagingSenderId: '209697579098',
    projectId: 'homelog-95dca',
    storageBucket: 'homelog-95dca.appspot.com',
    iosClientId: '209697579098-na2da9mt5elcg5epi8pongkncdibtfeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.p.RunnerTests',
  );
}
